image: harbor.tianxing.site/docker_hub/library/gradle:jdk8
stages:
  - test
  - build
  - push
  - deploy

cache:

test:
  stage: test
  script:
    - ./gradlew test

build:
  stage: build
  script:
    - ./gradlew bootjar

deploy:
  image: harbor.tianxing.site/docker_hub/library/docker:latest
  stage: deploy
  script:
    - docker login
    - docker push
    - kubectl -y apply